import React from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Image from "next/image";

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Indonesian Politicians</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="text-center pt-8">
        <h2 className="text-3xl">Indonesian Politicians</h2>
        <h5 className="text-lg capitalize mt-3">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae,
          fuga.
        </h5>
        <h5 className="text-sm">
          This Website Made with NextJS and Contentful CMS
        </h5>
      </div>
      <main className="my-8 flex justify-center">{children}</main>
      <footer className={styles.footer}>
        <a>pudy Development 092021 </a>
      </footer>
    </>
  );
}
